# Perfil 'prod' - Lê variáveis de ambiente do Render ou das chaves SPRING_ padrão
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL:}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
