# Perfil 'prod' - Usa variáveis de ambiente automaticamente via Relaxed Binding
# As variáveis de ambiente esperadas são:
# SPRING_DATASOURCE_URL
# SPRING_DATASOURCE_USERNAME
# SPRING_DATASOURCE_PASSWORD
# SPRING_DATASOURCE_DRIVER_CLASS_NAME
# SPRING_JPA_DATABASE_PLATFORM
# SPRING_JPA_HIBERNATE_DDL_AUTO
